version: '3.5'
services:
    web:
        build: . 
        image: busca_resolucoes:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"        
networks:
    default:
        external:
            name: sisat_default