# Generated by Django 3.2.5 on 2021-07-13 22:28

import ato.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SetorOriginario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Vigente'), (2, 'Revogada'), (2, 'Sem efeito')], default=None, null=True)),
                ('arquivo', models.FileField(blank=True, default=None, null=True, upload_to=ato.models.documento_file_name, verbose_name='Anexo')),
                ('assuntos', models.ManyToManyField(to='ato.Assunto')),
                ('setor_originario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ato.setororiginario')),
                ('tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ato.tipo')),
            ],
        ),
    ]
