# Generated by Django 3.2.5 on 2021-07-14 21:07

import ato.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SetorOriginario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Nome')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Resolução'), (1, 'Portaria'), (2, 'Edital'), (3, 'Deliberação'), (4, 'Instrução Normativa')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Vigente'), (2, 'Revogada'), (2, 'Sem efeito')])),
                ('texto', models.TextField(blank=True, default=None, null=True, verbose_name='Texto documento')),
                ('arquivo', models.FileField(default=None, null=True, upload_to=ato.models.documento_file_name, verbose_name='Arquivo')),
                ('assuntos', models.ManyToManyField(to='ato.Assunto')),
                ('setor_originario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ato.setororiginario')),
            ],
            options={
                'verbose_name': 'Ato',
                'verbose_name_plural': 'Documentos emitidos',
                'ordering': ['ano'],
            },
        ),
    ]
