# Generated by Django 3.2.8 on 2021-10-08 13:57

import ato.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ato',
            name='arquivo_02',
            field=models.FileField(blank=True, default=None, null=True, upload_to=ato.models.documento_file_name, verbose_name='PDF Pesquisável'),
        ),
        migrations.AddField(
            model_name='ato',
            name='arquivo_03',
            field=models.FileField(blank=True, default=None, null=True, upload_to=ato.models.documento_file_name, verbose_name='Arquivo editável (Word ou similar)'),
        ),
        migrations.AddField(
            model_name='ato',
            name='atos_vinculados',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_ato_ato_atos_vinculados_+', to='ato.Ato', verbose_name='Atos relacionados'),
        ),
        migrations.AddField(
            model_name='ato',
            name='data_final',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ato',
            name='data_inicial',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ato',
            name='documento_alterado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atos_alterados', to='ato.ato', verbose_name='Este documento altera outro? Caso positivo selecione o documento alterado'),
        ),
        migrations.AddField(
            model_name='ato',
            name='documento_revogado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atos_revogados', to='ato.ato', verbose_name='Este documento revoga outro? Caso positivo selecione o documento revogado'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='arquivo',
            field=models.FileField(default=None, null=True, upload_to=ato.models.documento_file_name, verbose_name='Extrato Dioe'),
        ),
    ]
