# Generated by Django 3.2.5 on 2021-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setororiginario',
            name='nome',
            field=models.TextField(blank=True, default=None, max_length=40, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descricao',
            field=models.TextField(blank=True, default=None, max_length=25, null=True, verbose_name='Descrição'),
        ),
    ]
