# Generated by Django 3.2.8 on 2021-10-19 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0002_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ato',
            name='data_documento',
            field=models.DateField(default=datetime.date(2021, 10, 19), verbose_name='Data do documento'),
        ),
    ]
