# Generated by Django 3.2 on 2021-10-20 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0003_alter_ato_data_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuntosecundario',
            name='assuntos',
        ),
        migrations.AddField(
            model_name='assunto',
            name='assuntos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='ato.AssuntoSecundario'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='data_documento',
            field=models.DateField(default=datetime.date(2021, 10, 20), verbose_name='Data do documento'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='numero',
            field=models.IntegerField(verbose_name='nº'),
        ),
    ]
