# Generated by Django 3.2 on 2021-11-20 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0005_aumenta_tamanho_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº da Edição')),
                ('data', models.DateField(default=datetime.date(2021, 11, 20), verbose_name='Data da publicação')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='ato',
            name='data_documento',
            field=models.DateField(default=datetime.date(2021, 11, 20), verbose_name='Data do documento'),
        ),
    ]
