# Generated by Django 3.2 on 2021-11-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0006_add_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ato',
            name='publicacao',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ato.publicacao'),
        ),
    ]
