# Generated by Django 3.2 on 2021-11-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0007_ato_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Tipo de ato',
                'verbose_name_plural': 'Tipos de atos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Nº da Edição'),
        ),
        migrations.AlterField(
            model_name='ato',
            name='tipo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ato.tipoato'),
        ),
    ]
