# Generated by Django 3.2 on 2021-11-30 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato', '0008_add_tipo_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ato',
            options={'ordering': ['ano'], 'verbose_name': 'Ato', 'verbose_name_plural': 'Atos'},
        ),
        migrations.AlterField(
            model_name='ato',
            name='data_documento',
            field=models.DateField(default=datetime.date(2021, 11, 30), verbose_name='Data do documento'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateField(default=datetime.date(2021, 11, 30), verbose_name='Data da publicação'),
        ),
    ]
